model_name_or_path: "google/gemma-3-1b-it"
behavior: "power-seeking"

# Extracting vectors from all 26 layers (0-25)
layer: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

vec_dir: "/kaggle/working/BiPO/vector/power-seeking_gemma-3"
eval_epoch: 18
